/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation
 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {


  // By default, Docusaurus generates a sidebar from the docs folder structure
  mySidebar: [{
    type: 'autogenerated', dirName: '.'
  }],

  // But you can create a sidebar manually
  // See: https://docusaurus.io/docs/sidebar
  /*
  mySidebar: [
    'intro',
    {
      type: 'category',
      label: 'Basics',
      link: {
        type: 'doc', 
        id: 'tutorial-basics/create-a-page'
      },
      items: [
        'tutorial-basics/create-a-document',
        'tutorial-basics/create-a-blog-post',
        'tutorial-basics/deploy-your-site',
        'tutorial-basics/markdown-features',
        'tutorial-basics/congratulations',
      ],
    },
    {
      type: 'category',
      label: 'Extras',
      link: {
        type: 'generated-index', 
        title: 'Docusaurus Guides',
        description: 'Learn about the most important Docusaurus concepts!',
        slug: '/category/tutorial-extras',
        keywords: ['extras'],
        image: '/img/docusaurus.png',
      },
      items: [
        'tutorial-extras/translate-your-site',
        'tutorial-extras/manage-docs-versions',
      ],
    },
  ],
  */

  // --------- Reference --------
  // Sidebars have: type, label, items[]
  //   Types can be doc, link, html, category or autogenerated

  // Use `doc` type to link to a doc page (i.e., collection)
  // See: https://docusaurus.io/docs/sidebar/items#sidebar-item-doc

  // Use type = `link` to link to any other internal/external page 
  // See: https://docusaurus.io/docs/sidebar/items#sidebar-item-link

  // Use type = 'html` to render custom HTML within the <li> tag
  // See: https://docusaurus.io/docs/sidebar/items#sidebar-item-html

  // Use type = `category` to dropdown list of items grouped by category label
  //    Set: collapsible=true - to have caret show for collapsing category
  //    Set: collapsed=true - to have default status be collapsed
  // See: https://docusaurus.io/docs/sidebar/items#sidebar-item-category


  // Use "Category" to create hierarchy of docs folders in sidebar
  //  The value of the "link.type" attribute can customize look of category landing page
  
  // 1. link: { type: 'generated-index'} 
  // Uses __category__.json (or yml) as source, generates page of cards
  // See: https://docusaurus.io/docs/sidebar/items#generated-index-page
  // Example: https://docusaurus.io/docs/category/guides
  /*
  docs: [
    {
      type: 'category',
      label: 'Guides',
      link: {
        type: 'generated-index',
        title: 'Docusaurus Guides',
        description: 'Learn about the most important Docusaurus concepts!',
        slug: '/category/docusaurus-guides',
        keywords: ['guides'],
        image: '/img/docusaurus.png',
      },
      items: ['pages', 'docs', 'blog', 'search'],
    },
  ],
  */

  // 1. link: { type: 'doc'} 
  // renders the document with the specified id as the landing page
  // See: https://docusaurus.io/docs/sidebar/items#category-doc-link
  // Example: https://docusaurus.io/docs/i18n/introduction
  /* 
  docs: [
    {
      type: 'category',
      label: 'Guides',
      link: {type: 'doc', id: 'introduction'},
      items: ['pages', 'docs', 'blog', 'search'],
    },
  ],
  */
 
};

module.exports = sidebars;
